### ISSUE TITLE
Why not creating a GitPage of the info?

### ISSUE THREAD

**Issue by berrydejager** [txavier/Saab#13]
I suggest creating a GitPage on it's own domain (just like [Tech2wiki.com](https://github.com/tech2wiki/tech2wiki-website)) for a better visibility for other SAAB owners.

If you like, i can help out.

**Comment by txavier** [comment]
Sorry, I have no knowledge of a gitpage.  By all means, please yes go ahead and set this up.

**Comment by berrydejager** [comment]
See here: https://docs.github.com/en/pages/quickstart for advanced static pages: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll
